  
# 核心任务

- name: SqlServer
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  




  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: sqlserver, tags: "sqlserver"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}
