# install SqlServer by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure SqlServer

- name: install sqlserver
  shell: 
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    apt-get install software-properties-common 
    sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/18.04/mssql-server-2017.list)"
    sudo apt-get update
    sudo apt-get install -y mssql-server

- name: install sqlcmd and bcp
  shell:
    curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
    sudo apt-get update 
    sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

- name: Set Environment
  shell:
    echo 'export PATH="$PATH:/opt/mssql-tools/bin' >> ~/.bash_profile
    source ~/.bash_profile
    echo 'export PATH="$PATH:/opt/mssql-tools/bin' >> ~/.bashrc
    source ~/.bashrc

- name: Create mssql User
  user:
    name: mssql
    shell: /usr/sbin/nologin
    home:  /opt/mssql/bin/sqlserver
    create_home: no


- name: Set SqlServer pwd  
  shell:
    MSSQL_SA_PASSWORD='{{sqlserver_db_password}}' MSSQL_PID='express' /opt/mssql/bin/mssql-conf -n setup accept-eula


- name: Restart SqlServer
  service:
    name: mssql-server.service
    state: restarted
    enabled: yes

- name: Create SqlServer directory for files
  file:
    path: /data/wwwroot/SqlServer
    state: directory
    owner: mssql
    group: mssql


- name: Create the storage directory for files.
  file:
      path: /data/config/SqlServer
      state: directory 
      owner: mssql 
      group: mssql
      mode: g+w  

# set soft link, -b cover the exist links
# ln -sb src des
- name: set soft link
  shell: 
    ln -sb /lib/systemd/system/mssql-server.service /lib/systemd/system/sqlserver.service
    ln -sb /opt/mssql/bin/sqlserver  /data/wwwroot/SqlServer
    ln -sb /opt/mssql/bin/mssql-conf /data/config/SqlServer

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check SqlServer Version
    shell: 
     rpm -qa |grep mssql     


# check service state
- name: Check SqlServer Service
  shell: systemctl status sqlserver |grep Active*
  register: check_sqlserver_service
  notify: check_sqlserver_service

