#1 install SqlServer by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"


#2 configure
- name: Set Environment for mssql-tools
  shell: |
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

- name: Create system user named mssql
  user:
    name: mssql
    shell: /usr/sbin/nologin
    home:  /opt/mssql/bin/sqlserver
    create_home: no

- name: Set SQLServer SA password and version
  shell: |
    systemctl stop mssql-server
    sudo MSSQL_SA_PASSWORD='{{sqlserver_sa_password}}' \
    MSSQL_PID='{{sqlserver_distribution}}' \
    /opt/mssql/bin/mssql-conf -n setup accept-eula

- name: Started SQLServer
  service:
    name: mssql-server.service
    enabled: yes
  
- name: Create SQLServer directory for files
  file:
    path: /data/wwwroot/sqlserver
    state: directory
    owner: mssql
    group: mssql

- name: Create the storage directory for files.
  file:
    path: /data/config/sqlserver
    state: directory 
    owner: mssql 
    group: mssql
    mode: g+w  

# set soft link, -b cover the exist links
- name: set soft link
  shell: |
    ln -sb /lib/systemd/system/mssql-server.service /lib/systemd/system/sqlserver.service
    ln -sb /opt/mssql/bin/  /data/wwwroot
    ln -sb /opt/mssql/lib/  /data/config

# Check version
- block:
  - name: Check SQLServer Version
    shell: echo `dpkg -l |grep mssql-server || rpm -qa |grep mssql-server` >> /data/logs/install_version.txt

# check service state
- name: Check SqlServer Service
  shell: systemctl status sqlserver |grep Active*
  register: check_sqlserver_service
  notify: check_sqlserver_service
